apiVersion: v1
kind: Pod
metadata:
  name: pod-with-volume
  labels:
    name: pod-with-volume
spec:
  containers:
  - name: c1
    image: busybox
    volumeMounts:
      - mountPath: /tmp/c1volume
        name: volex # volume+example
    command:
      - "sh"
      - "-c"
      - "sleep 3600"
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
  - name: c2
    image: busybox
    volumeMounts:
      - mountPath: /tmp/c2volume
        name: volex # volume+example
    command:
      - "sh"
      - "-c"
      - "sleep 3600"
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
  volumes:
    - name: volex
      emptyDir: {}
        
