apiVersion: v1
kind: Pod
metadata:
  name: pod-with-resource-limits
  labels:
    env: production
    created-by: Vinod
    team: ev
spec:
  containers:
    - name: fsc-container
      image: learnwithvinod/flask-customer-service:latest
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "64Mi"
          cpu: "500m"

#  1062  kubectl get pods
#  1063  kubectl get pods --show-labels
#  1064  kubectl get pods --selector created-by=Vinod
#  1065  kubectl get pods --selector env=production
#  1066  kubectl get pods --selector env=development
#  1067  kubectl get pods --selector team=infosys
#  1068  kubectl get pods --selector team=ev
#  1069  kubectl label pods twocontainers env=development
#  1070  kubectl label pods twocontainers team=ev
#  1072  kubectl get pods --show-labels
#  1073  kubectl get pods --selector team=ev
#  1074  kubectl get pods --selector env=development
#  1075  kubectl get pods --selector env=production
#  1076  kubectl get pods -l env=production
