apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  containers:
    - name: fcs
      image: learnwithvinod/flask-customer-service:latest
      ports:
        - containerPort: 8080
    - name: bbox
      image: busybox
      command: 
        - "sh"
        - "-c"
        - "sleep 1000"


# to run this configuration
# minikube kubectl -- apply -f ./pod.yml
# kubectl apply -f ./pod.yml
# minikube kubectl -- get pods
# minikube kubectl -- describe pod twocontainers