apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcs-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: fcs
  template:
    metadata:
      labels:
        app: fcs
    spec:
      containers:
        - name: fcs
          image: learnwithvinod/flask-customer-service:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: fcs-service
spec:
  ports:
    - port: 8888
      targetPort: 8080
  selector:
    app: fcs

# kubectl port-forward services/fcs-service 7777:8888
# curl localhost:7777/api/customers
# curl <ubuntu-ip>:7777/api/customers
