version: "3.8"

services:

  mysql-service:
    image: "mysql:latest"
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=Welcome#123"
    volumes:
      - "mysql_data:/var/lib/mysql"

    
  customer-service:
    build: ./customer-service
    container_name: customer-service-container
    ports:
      - "9090:9090"
    depends_on:
      - mysql-service
    environment:
      - "MYSQL_HOST=mysql-service"


volumes:
  mysql_data:
    external: true
      