apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcs-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: fcs
  template:
    metadata:
      labels:
        env: development
        created-by: Vinod
        team: ev
        app: fcs
    spec:
      containers:
        - name: fcs
          image: learnwithvinod/flask-customer-service:latest
          env:
            - name: APP_VERSION
              value: "1.5.0"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
    